### ISSUE TITLE
go test failed with dynamodb_locl

### ISSUE THREAD

**Issue by iNickGo** [AdRoll/goamz#349]
Hi AdRoll:

I got the following two failed test cases with 2014-10-17, but it is ok with the latest one,
I do a minor modification in https://github.com/iNickGo/goamz/commit/9d26420e65792068d656819ff9ff361a76edbc24
Do you think this modification a good idea  ?

Regards,
Nick

FAIL: item_test.go:572: ItemSuite.TestQueryScanWithMap

item_test.go:612:
    c.Fatal(err)
... Error: InternalFailure: The request processing has failed because of an unknown error, exception or failure.

----------------------------------------------------------------------
FAIL: item_test.go:572: ItemSuite.TestQueryScanWithMap

item_test.go:612:
    c.Fatal(err)
... Error: InternalFailure: The request processing has failed because of an unknown error, exception or failure.

**Comment by alimoeeny** [comment]
Hi Nick, 
Would you mind separating the `local` tests and `real` (on real AWS) tests. So that people can do `make testlocal` or `make testreal` or something like that. 
And I don't know why that error happens, Hopefully others will chime in.
Cheers,
Ali

**Comment by iNickGo** [comment]
Hi Ali:

Local tests and real tests were already separated.
The original Makefile is for downloading dynamodb_local_jar and runs it at port 8000, after that, we can  use "go test -amazon to test local one". If we use "go test -amazon -local=false" to test real one.

But just like your suggest, we can write some lines in Makefile for convenience, but I am not sure if this is conventional for Go, what do you think ?  : )

Regards,
Nick

**Comment by alimoeeny** [comment]
Hey Nick, 
Sorry, so I misunderstood the whole thing. 
Yeah, I think it is a good idea to always test against the latest local-dynamodb. As it is a moving target and you want to keep yourself always up to speed with the changes. 
Ali
