### ISSUE TITLE
Bug in s3.New, struct member position incorrect.

### ISSUE THREAD

**Issue by ziyan** [AdRoll/goamz#351]
I found this when trying to use V4Signature for S3 (V4 is required in some AWS regions):
https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L98

```
// New creates a new S3.
func New(auth aws.Auth, region aws.Region) *S3 {
	return &S3{auth, region, 0, 0, 0, aws.V2Signature}
}
```

Should be:

```
// New creates a new S3.
func New(auth aws.Auth, region aws.Region) *S3 {
	return &S3{auth, region, 0, 0, aws.V2Signature, 0}
}
```

**Comment by alimoeeny** [comment]
@ziyan  You are right. 
It looks like in 6251102 when the `signature` was first added to the S3 struct the `new` got the params in the wrong order.
Would you mind sending a PR ?

**Comment by ziyan** [comment]
See PR #353
