### ISSUE TITLE
Add support for AWS China EndPoint

### ISSUE THREAD

**Issue by iyee** [AdRoll/goamz#360]
**cn-north-1** endpoint could cause a panic

`
Invalid region provided
`

reference link is [here](http://docs.amazonaws.cn/en_us/general/latest/gr/isolated_regions.html)

**Comment by alimoeeny** [comment]
@iyee  please update the https://github.com/AdRoll/goamz/blob/master/aws/regions.go and send a pull request. 
Thanks.

**Comment by iyee** [comment]
https://github.com/AdRoll/goamz/pull/362/files
