### ISSUE TITLE
TYPE_BOOL : Missing NewBoolAttribute

### ISSUE THREAD

**Issue by nalin-humin** [AdRoll/goamz#384]

**Comment by alimoeeny** [comment]
What?

**Comment by nalin-humin** [comment]
Shouldn't we have NewBoolAttribute() defined in item.go? Like, we have NewBinaryAttribute()

**Comment by alimoeeny** [comment]
I'd say we should? Although, personally, I have this old fashioned habbit of only using `S` (string attributes). But if you've got a few minutes to spare, please send a pull request.

**Comment by nalin-humin** [comment]
sure - https://github.com/AdRoll/goamz/pull/385
